// Verified Techfest, IIT Bombay official metadata & content

export const SITE_METADATA = {
  title: "Techfest — The Future Is Built Here | IIT Bombay",
  description: "Official landing page concept for Techfest, IIT Bombay — Asia's Largest Science and Technology Festival.",
  location: "IIT Bombay, Powai, Mumbai, India",
  edition: "28th Edition",
  coordinates: "19.1334° N, 72.9133° E",
  established: "1998",
};

export const NAV_LINKS = [
  { name: "EXPLORE", href: "#hero" },
  { name: "EVENTS", href: "#categories" },
  { name: "RADAR", href: "#radar" },
  { name: "ROBOWARS", href: "#robowars" },
  { name: "COMPETITIONS", href: "#competitions" },
  { name: "EXPERIENCE", href: "#experience" },
];

export const STATS = [
  {
    value: 175,
    suffix: "K+",
    label: "ANNUAL FOOTFALL",
    subtext: "Global tech enthusiasts & innovators",
  },
  {
    value: 300,
    suffix: "+",
    label: "EVENTS & CHALLENGES",
    subtext: "Competitions, workshops & exhibitions",
  },
  {
    value: 2500,
    suffix: "+",
    label: "COLLEGES ENGAGED",
    subtext: "Pan-India & international institutions",
  },
  {
    value: 28,
    suffix: "TH",
    label: "EDITION OF INNOVATION",
    subtext: "Pioneering technological excellence since 1998",
  },
];

export const CATEGORIES = [
  {
    id: "01",
    tag: "COMPETE",
    title: "Competitions",
    subtitle: "High-stakes technical arenas testing engineering rigor",
    description: "From international combat robotics to algorithmic challenges and open hackathons, compete against top minds globally.",
    icon: "Trophy",
    metrics: "50+ Challenges",
    color: "from-cyan-500/20 to-blue-500/5",
    accent: "#00F0FF",
  },
  {
    id: "02",
    tag: "LEARN",
    title: "Workshops",
    subtitle: "Hands-on masterclasses led by industry pioneers",
    description: "Deep dive into Artificial Intelligence, Deep Learning, Quantum Computing, Cyber Security, and Autonomous Robotics.",
    icon: "Cpu",
    metrics: "40+ Masterclasses",
    color: "from-purple-500/20 to-indigo-500/5",
    accent: "#8B5CF6",
  },
  {
    id: "03",
    tag: "DISCOVER",
    title: "Exhibitions",
    subtitle: "Window to tomorrow's breakthrough tech",
    description: "Showcasing humanoid robots, space telemetry, defense technology, and futuristic prototypes from top global labs.",
    icon: "Globe",
    metrics: "International Expo",
    color: "from-emerald-500/20 to-teal-500/5",
    accent: "#10B981",
  },
  {
    id: "04",
    tag: "CONNECT",
    title: "Lectures",
    subtitle: "Keynotes by Nobel Laureates & Visionaries",
    description: "Inspirational addresses from Nobel prize winners, space scientists, tech founders, and global policy makers.",
    icon: "Mic",
    metrics: "25+ Keynotes",
    color: "from-amber-500/20 to-orange-500/5",
    accent: "#F59E0B",
  },
  {
    id: "05",
    tag: "BATTLE",
    title: "Robowars",
    subtitle: "Asia's premier international combat robotics battleground",
    description: "Heavyweight steel-crushing bots clash inside a bulletproof arena with high-energy arena tactical combat.",
    icon: "Swords",
    metrics: "Heavyweight Arena",
    color: "from-red-500/20 to-rose-500/5",
    accent: "#EF4444",
  },
  {
    id: "06",
    tag: "EXPERIENCE",
    title: "Technoholix & Ozone",
    subtitle: "Immersive nightlife, laser spectacles & informal zones",
    description: "Mesmerizing nightshows, international tech performances, gaming lounges, and experiential tech installations.",
    icon: "Sparkles",
    metrics: "Nightly Spectacles",
    color: "from-fuchsia-500/20 to-pink-500/5",
    accent: "#EC4899",
  },
];

export const RADAR_NODES = [
  {
    id: "robowars",
    label: "ROBOWARS",
    category: "Combat Arena",
    x: 20, // percentage from center
    y: -30,
    stats: "120kg Heavyweight Class",
    description: "International combat robotics championship. Custom titanium spinners and hydraulic flippers battle inside a hardened steel arena.",
    highlight: "International Teams",
    icon: "Swords",
  },
  {
    id: "workshops",
    label: "WORKSHOPS",
    category: "Hands-on Learning",
    x: 35,
    y: 10,
    stats: "Certified Hands-on",
    description: "Certified masterclasses on Generative AI, Edge Computing, Autonomous Drones, and Quantum Mechanics.",
    highlight: "Industry Certification",
    icon: "Cpu",
  },
  {
    id: "exhibitions",
    label: "EXHIBITIONS",
    category: "Global Tech Expo",
    x: 10,
    y: 35,
    stats: "25+ Nations",
    description: "Futuristic prototypes including Boston Dynamics humanoids, hyperloop pod models, and space rover telemetry.",
    highlight: "Cutting-edge Prototypes",
    icon: "Globe",
  },
  {
    id: "lectures",
    label: "LECTURES",
    category: "Keynote Sessions",
    x: -25,
    y: 30,
    stats: "Nobel Laureates",
    description: "Keynote talks by world leaders in science, fields medalists, astronauts, and founders reshaping technology.",
    highlight: "Global Visionaries",
    icon: "Mic",
  },
  {
    id: "competitions",
    label: "COMPETITIONS",
    category: "Tech Challenges",
    x: -35,
    y: -15,
    stats: "Pan-Asia Track",
    description: "Flagship competitions including CozmoClench, Meshmerize, HackAI, and International Autonomous Bot Challenges.",
    highlight: "High-Stakes Arena",
    icon: "Trophy",
  },
  {
    id: "technoholix",
    label: "TECHNOHOLIX",
    category: "Night Shows",
    x: -15,
    y: -35,
    stats: "Open-Air Arena",
    description: "The ultimate synthesis of technology and entertainment: pyrotechnics, drone light shows, and international artists.",
    highlight: "Laser & Drone FX",
    icon: "Sparkles",
  },
];

export const COMPETITIONS = [
  {
    id: "comp-1",
    code: "ROBO-01",
    title: "Robowars International",
    category: "Combat Robotics",
    tagline: "Steel meets speed inside Asia's fiercest combat cage.",
    description: "Design and build remote-controlled combat robots (60kg & 120kg categories). Survive intense round-robin elimination rounds.",
    techSpecs: "Pneumatics, Hydraulics, Armor Metallurgy",
    prize: "Major Cash Prize + Trophy",
    status: "REGISTRATIONS OPEN",
    color: "#EF4444",
  },
  {
    id: "comp-2",
    code: "AUTO-02",
    title: "CozmoClench",
    category: "Gripper Robotics",
    tagline: "Autonomous pick-and-place precision under strict time limits.",
    description: "Build an autonomous or semi-autonomous bot capable of navigating complex line grids, detecting color payloads, and placing targets.",
    techSpecs: "IR Sensors, Microcontrollers, Servo Grippers",
    prize: "Techfest Official Certification",
    status: "GRID READY",
    color: "#00F0FF",
  },
  {
    id: "comp-3",
    code: "ALGO-03",
    title: "Meshmerize",
    category: "Maze Solvers",
    tagline: "Line-following & dynamic maze algorithm speed trial.",
    description: "Autonomous micro-mouse and maze-solving robots calculate shortest paths in real-time using advanced flood-fill algorithms.",
    techSpecs: "PID Control, Encoders, Dynamic Pathing",
    prize: "Pan-Asia Recognition",
    status: "REGISTRATIONS OPEN",
    color: "#8B5CF6",
  },
  {
    id: "comp-4",
    code: "AI-04",
    title: "Techfest HackAI",
    category: "Artificial Intelligence",
    tagline: "36-Hour hackathon building real-world AI agents & LLMs.",
    description: "Tackle grand challenges in computer vision, generative AI, and climate modeling using state-of-the-art open source models.",
    techSpecs: "PyTorch, CUDA, Agentic Frameworks",
    prize: "Incubation Grants + Cloud Credits",
    status: "LIVE CHALLENGE",
    color: "#10B981",
  },
  {
    id: "comp-5",
    code: "AERO-05",
    title: "SkyTrace Aeromodelling",
    category: "Aeronautics",
    tagline: "Custom RC aircraft design, payload drop & agility trial.",
    description: "Engineered fixed-wing RC aircraft designed for optimal lift-to-drag ratio and precise payload deployment in windy conditions.",
    techSpecs: "Aerodynamics, Composite Materials, Telemetry",
    prize: "Boeing / Aerospace Industry Perks",
    status: "FLIGHT DECK",
    color: "#F59E0B",
  },
];
